2019-05-25 12:27:43 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 12:27:44 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 12:27:44 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 12:27:44 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 12:28:18 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 12:28:18] "POST /v1/mobile/client/register HTTP/1.1" 200 -
2019-05-25 13:37:02 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:37:03 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:37:03 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:37:03 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:37:11 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:37:11 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:37:11] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:38:07 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:38:07 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:38:08 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:38:08 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:38:08 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:38:08 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:38:08 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:38:08] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:39:57 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:39:59 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:39:59 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:39:59 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:41:33 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:41:33 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:41:33] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:43:18 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:43:18 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:43:18] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:44:24 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:44:24 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:44:25 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:44:25 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:44:25 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:44:27 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:44:27 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:44:28 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:44:28 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:44:28 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:44:30 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:44:30 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:44:32 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:44:32 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:44:32 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:44:33 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:44:33 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:44:35 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:44:35 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:44:35 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:44:36 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:44:36 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:44:37 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:44:37 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:44:37 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:44:52 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:44:52 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:44:54 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:44:54 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:44:54 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:45:03 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:45:04 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:45:04 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:45:04 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:45:13 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:45:13 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:45:13] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:45:41 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:45:43 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:45:43 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:45:43 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:45:43 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:45:43 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:45:43] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:46:35 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:46:37 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:46:37 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:46:37 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:46:37 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:46:37 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:46:37] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:46:43 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:46:44 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:46:44 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:46:44 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:46:44 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:46:44 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:46:44] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:48:32 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:48:33 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:48:33 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:48:33 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:48:35 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:48:35 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:48:35] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:48:38 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:48:38 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:48:38] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:48:41 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:48:41 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:48:41] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:48:47 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:48:48 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:48:48 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:48:48 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:48:55 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:48:55 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:48:55] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:49:24 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:49:24 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:49:25 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:49:25 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:49:25 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:49:26 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:49:26 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:49:26] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:50:09 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:50:09 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:50:10 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:50:10 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:50:10 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:50:10 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:50:10 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:50:10] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:50:19 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:50:19 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:50:19] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:50:24 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:50:26 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:50:26 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:50:26 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:50:26 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:50:26 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:50:26] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:50:58 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:50:58 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:50:58] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:51:10 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:51:11 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:51:11 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:51:11 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:51:18 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:51:18 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:51:18] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:52:38 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 40, in get_token
    expiration
  File "D:\cake\flask-admin\api\app\api\mobile\v1\token.py", line 58, in generate_auth_token
    'type': ac_type.value,
TypeError: dump() missing 1 required positional argument: 'f'
2019-05-25 13:52:38 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:52:38] "POST /v1/mobile/token HTTP/1.1" 500 -
2019-05-25 13:54:51 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:54:51 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:54:51 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:54:51 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:54:58 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:54:58] "POST /v1/mobile/token HTTP/1.1" 200 -
2019-05-25 13:55:07 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:55:07 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:55:08 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:55:08 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:55:08 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:55:08 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:55:08] "POST /v1/mobile/token HTTP/1.1" 200 -
2019-05-25 13:55:36 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\token.py', reloading
2019-05-25 13:55:36 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 13:55:37 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 13:55:37 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 13:55:37 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 13:55:37 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 13:55:37] "POST /v1/mobile/token HTTP/1.1" 200 -
2019-05-25 14:04:09 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:04:09] "POST /v1/mobile/token HTTP/1.1" 404 -
2019-05-25 14:05:25 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:05:25] "POST /v1/mobile/client/register HTTP/1.1" 400 -
2019-05-25 14:05:47 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:05:47] "POST /v1/mobile/client/register HTTP/1.1" 400 -
2019-05-25 14:06:52 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:06:52] "POST /v1/mobile/client/register HTTP/1.1" 400 -
2019-05-25 14:08:18 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:08:18] "POST /v1/mobile/client/register HTTP/1.1" 400 -
2019-05-25 14:08:23 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:08:24 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:08:24 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:08:24 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:08:26 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:08:27 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:08:27 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:08:27 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:08:33 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:08:33] "POST /v1/mobile/client/register HTTP/1.1" 400 -
2019-05-25 14:09:35 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:09:36 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:09:36 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:09:36 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:09:38 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:09:39 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:09:39 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:09:39 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:10:37 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:10:38 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:10:38 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:10:38 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:10:41 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:10:41] "POST /v1/mobile/client/register HTTP/1.1" 400 -
2019-05-25 14:11:36 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:11:37 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:11:37 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:11:37 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:12:19 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:12:19] "POST /v1/mobile/client/register HTTP/1.1" 200 -
2019-05-25 14:30:53 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:30:54 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:30:54 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:30:54 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:31:02 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:31:02] "POST /v1/mobile/token HTTP/1.1" 404 -
2019-05-25 14:31:39 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 14:31:39] "POST /v1/mobile/token HTTP/1.1" 200 -
2019-05-25 14:33:18 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 14:33:18 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:33:19 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:33:19 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:33:19 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:33:29 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 14:33:29 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:09 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:09 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:09 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:09 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:26 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:26 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:27 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:27 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:27 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:30 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:30 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:31 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:31 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:31 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:33 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:33 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:34 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:34 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:34 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:35 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:35 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:36 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:36 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:36 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:38 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:38 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:39 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:39 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:39 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:41 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:41 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:42 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:42 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:42 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:47 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:47 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:47 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:47 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:47 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:56:53 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:56:53 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:56:54 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:56:54 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:56:54 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:57:28 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:57:28 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:57:28 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:57:28 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:57:28 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:57:35 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:57:35 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:57:36 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:57:36 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:57:36 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:57:38 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:57:38 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:57:39 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:57:39 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:57:39 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:57:44 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:57:44 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:57:44 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:57:44 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:57:44 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 14:57:48 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 14:57:48 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 14:57:49 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 14:57:49 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 14:57:49 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:00:59 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\token_auth.py', reloading
2019-05-25 15:00:59 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:01:00 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:01:00 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:01:00 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:02:52 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:02:53 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:02:53 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:02:53 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:21:35 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:21:36 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:21:36 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:21:36 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:21:43 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:21:43] "GET /v1/mobile/user HTTP/1.1" 200 -
2019-05-25 15:22:11 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:22:11] "GET /v1/mobile/user HTTP/1.1" 401 -
2019-05-25 15:22:28 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:22:28] "GET /v1/mobile/user HTTP/1.1" 200 -
2019-05-25 15:24:06 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:24:06] "GET /v1/mobile/user HTTP/1.1" 200 -
2019-05-25 15:25:19 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:25:19] "GET /v1/mobile/user HTTP/1.1" 401 -
2019-05-25 15:27:44 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:27:44 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:27:44 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:27:44 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:30:13 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 15:30:13 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:30:14 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:30:14 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:30:14 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:30:17 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 15:30:17 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:30:18 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:30:18 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:30:18 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:30:21 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 15:30:21 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:59:04 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:59:05 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:59:05 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:59:05 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:59:06 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask_httpauth.py", line 62, in decorated
    return f(*args, **kwargs)
TypeError: getUser() missing 1 required positional argument: 'uid'
2019-05-25 15:59:06 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:59:06] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 15:59:16 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:59:17 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:59:17 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:59:17 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:59:18 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask_httpauth.py", line 62, in decorated
    return f(*args, **kwargs)
TypeError: getUser() missing 1 required positional argument: 'uid'
2019-05-25 15:59:18 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:59:18] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 15:59:23 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:59:25 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:59:25 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:59:25 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:59:25 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask_httpauth.py", line 62, in decorated
    return f(*args, **kwargs)
TypeError: getUser() missing 1 required positional argument: 'uid'
2019-05-25 15:59:25 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:59:25] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 15:59:52 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 15:59:53 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 15:59:53 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 15:59:53 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 15:59:57 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask_httpauth.py", line 62, in decorated
    return f(*args, **kwargs)
TypeError: getUser() missing 1 required positional argument: 'uid'
2019-05-25 15:59:57 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 15:59:57] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 16:00:07 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:00:09 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:00:09 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:00:09 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:00:11 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask_httpauth.py", line 62, in decorated
    return f(*args, **kwargs)
TypeError: getUser() missing 1 required positional argument: 'uid'
2019-05-25 16:00:11 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 16:00:11] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 16:00:15 cake.py[line:44] ERROR Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\.virtualenvs\api-p84yQ-z8\lib\site-packages\flask_httpauth.py", line 62, in decorated
    return f(*args, **kwargs)
TypeError: getUser() missing 1 required positional argument: 'uid'
2019-05-25 16:00:15 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 16:00:15] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 16:00:51 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:00:52 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:00:53 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:00:53 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:00:53 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 16:00:53] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 16:01:01 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:01:02 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:01:02 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:01:02 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:11:59 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:12:00 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:12:00 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:12:00 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:19:21 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:19:21 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:19:22 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:19:22 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:19:22 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:19:25 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:19:25 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:19:26 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:19:26 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:19:26 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:19:42 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:19:42 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:19:43 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:19:43 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:19:43 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:19:47 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:19:47 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:19:48 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:19:48 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:19:48 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:19:51 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:19:51 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:19:52 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:19:52 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:19:52 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:19:59 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:19:59 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:20:00 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:20:00 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:20:00 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:20:20 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:20:24 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:20:24 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:20:24 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:26:37 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 16:26:37 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:32:41 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:32:41 _internal.py[line:122] INFO  * Debugger PIN: 234-277-292
2019-05-25 16:32:41 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 16:33:30 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:36:11 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 16:36:12 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 16:36:12 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 16:36:12 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:03:42 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:03:43 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:03:43 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:03:43 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:03:45 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:03:45] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:04:31 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 17:04:31 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:04:32 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:04:32 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:04:32 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:04:34 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:04:34] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:11:06 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 17:11:07 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:11:07 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:11:07 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:11:07 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:11:08 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:11:08] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:12:04 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 17:12:04 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:12:04 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:12:04 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:12:04 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:12:06 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:12:06] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 17:12:29 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 17:12:29 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:12:30 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:12:30 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:12:30 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:12:30 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:12:30] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:13:35 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\error.py', reloading
2019-05-25 17:13:35 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:13:36 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:13:36 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:13:36 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:13:37 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:13:37] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 17:13:58 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\libs\\error.py', reloading
2019-05-25 17:13:58 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:13:59 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:13:59 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:13:59 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:14:15 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:14:16 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:14:16 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:14:16 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:14:51 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:14:51] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 17:15:10 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 17:15:10 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:15:12 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:15:12 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:15:12 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:15:16 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:15:16] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:16:49 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\api\\mobile\\v1\\user.py', reloading
2019-05-25 17:16:49 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:16:51 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:16:51 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:16:51 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:16:55 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:16:55] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:17:07 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\models\\user.py', reloading
2019-05-25 17:17:07 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:17:08 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:17:08 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:17:08 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:17:09 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:17:09] "GET /v1/mobile/user?uid=10 HTTP/1.1" 500 -
2019-05-25 17:17:15 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\models\\user.py', reloading
2019-05-25 17:17:15 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:17:17 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:17:17 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:17:17 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:17:17 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:17:17] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:17:52 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:17:52] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:19:45 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\models\\user.py', reloading
2019-05-25 17:19:45 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:19:46 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:19:46 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:19:46 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:23:02 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\models\\user.py', reloading
2019-05-25 17:23:02 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:23:04 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:23:04 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:23:04 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:34:46 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\app.py', reloading
2019-05-25 17:34:46 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:34:48 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:34:48 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:34:48 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:34:49 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\app.py', reloading
2019-05-25 17:34:49 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:42:13 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:42:14 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:42:14 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:42:14 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:42:16 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:42:16] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
2019-05-25 17:43:52 _internal.py[line:122] INFO  * Detected change in 'D:\\cake\\flask-admin\\api\\app\\app.py', reloading
2019-05-25 17:43:52 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:47:14 _internal.py[line:122] INFO  * Restarting with stat
2019-05-25 17:47:15 _internal.py[line:122] WARNING  * Debugger is active!
2019-05-25 17:47:15 _internal.py[line:122] INFO  * Debugger PIN: 710-284-662
2019-05-25 17:47:15 _internal.py[line:122] INFO  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-05-25 17:47:18 _internal.py[line:122] INFO 127.0.0.1 - - [25/May/2019 17:47:18] "GET /v1/mobile/user?uid=10 HTTP/1.1" 200 -
